### ISSUE TITLE
[feature request] formatting options for endnotes equivalent to footnotes

### ISSUE THREAD

**Issue by floriandk** [maieul/ledmac#335]
Some formatting options for footnotes that I'd need don't have equivalents for endnotes:

    \Xhangindent
    \numberonlyfirstinline
    \numberonlyfirstintwolines
    \inplaceofnumber

It would be good also to have a similar mechanism ("`\pagenumberonlyfirstinline`" and "`\ pagenumberonlyfirstintwolines`") for page-numbers to make it possible to produce something like:

    p. 1
         1  xxx] yyy, AB
             a] b, BC
             qwert] azer, C
         2  ccc] ddd, AE
         5  eee] fff, AD
    
    […]
    
    p. 2
         2  uuu] + u, C
         4–6  sdf–ghj] Duis fermentum, metus
                      sed congue gravida, arcu dui
                      ornare urna, ut imperdiet enim
                      odio dignissim ipsum., A
         8  klm] om. ABC

At some point I think it would be most logical to have complete pairs of this type of formatting options, (as long as they make sense anyway) for both foot- and endnotes.
I'd also suggest to summarize these pairs in a table somewhere in the doc (Appendix?) in the end for easy reference.

**Comment by maieul** [comment]
> 
> At some point I think it would be most logical to have complete pairs of this type of formatting options, (as long as they make sense anyway) for both foot- and endnotes.
> I'd also suggest to summarize these pairs in a table somewhere in the doc (Appendix?) in the end for easy reference.


formally, you are right. But as I am alone maintener, I prefer to add them when people ask for it...

**Comment by floriandk** [comment]
very understandable!
BTW: no great hurry with this feature; the book in question will probably not be typeset before late this year

**Comment by maieul** [comment]
please also send a MWE (for \Xhangindent, you could juste set \hangindent before calling endnotes).

**Comment by maieul** [comment]
please send a mwe

**Comment by maieul** [comment]
hi @floriandk please send mwe

**Comment by arthurali** [comment]
@maieul hi, I have the same problem as @floriandk: I would need the option to not number the second (third, etc.) endnote in one line, as it is possible for footnotes using "\numberonlyfirstinline". Since you haven't received a mwe yet, I thought, I might provide one: 


\documentclass{scrartcl}
\usepackage[ngerman]{babel}

\usepackage{eledmac}
\begin{document}

    \beginnumbering
    \numberonlyfirstinline
    \pstart
    \edtext{Wort1}{\Afootnote{Apparat}\Aendnote{Kommentar}} und noch
ein \edtext{Wort2}{\Afootnote{Apparat}\Aendnote{Kommentar}}

    Noch ein \edtext{Wort3}{\Afootnote{Apparat}\Aendnote{Kommentar}}
    \pend
    \endnumbering
    \newpage
    \doendnotes{A}

\end{document} 

I am quite new to all of this, so please forgive me (and notify me) if there is something wrong. Many thanks!

**Comment by maieul** [comment]
thanks, I will do it this week-end

**Comment by arthurali** [comment]
Thank you!

**Comment by maieul** [comment]
@floriandk  and @arthurali : please try branch issue335. I have implemented
- \Xendnumberonlyfirstinline
- \Xendnumberonlyfirstintwolines 
- \Xendsymlinenum 
- \Xendbeforenumber 
- \Xendafterenumber 
- \Xendbeforesymlinenum 
- \Xendaftersymlinenum 
- \Xendboxsymlinenum 
- \Xendhangindent

**Comment by maieul** [comment]
hi @arthurali do you think to have time to test in next days? I would like to include this patch in next release (next week?)

**Comment by arthurali** [comment]
hi @maieul thank you very much for the new code! I'll tell you our "test results" with patch "Xendnumberonlyfirstinline" tomorrow latest.

**Comment by ingoboerner** [comment]
Dear @maieul, 
@arthurali and I tested the new feature "Xendnumberonlyfirstinline" and it works fine with the MWE. We also tested it in our production environment, which we updated to reledmac. There it also works, but we still have some issues, which might be not directly conected to the new features:
When we add the new code, we get this output, which is good:
![output](https://cloud.githubusercontent.com/assets/12182347/10048975/cf4277f4-6215-11e5-9adc-0b12d2ef1c96.png)
There is a space between the two endnotes in line 10, which is the same as between all other notes (to produce it, we use "\Xendbhooknote[B]{\vspace{1em}}")
We would like to reduce the space between the notes in the same line, so that it looks like that:
![desired_output](https://cloud.githubusercontent.com/assets/12182347/10048990/dbe610b0-6215-11e5-8d84-0d876b637b3c.png)
In the example above we used "\Xendinplaceofnumber[B]{\vspace{-2em}}". This produces the right output, but we get an error message "Illegal unit of measure (pt inserted). an.}}{B}{}". As stated in the documentation, "Xendinplaceofnumber" expects a length, not arbitrary code.

Is there a better way to add vertical space between endnotes and omit the space, if there are two or more endnotes in one line?

I tried to produce a kind of MWE:

\documentclass{scrartcl}
\usepackage[ngerman]{babel} 
\usepackage{reledmac}

% KOMMENTAR

%% Layout
\renewcommand*{\printnpnum}[1]{} %omits output of p.
\Xendbhooknote[A]{\vspace{1em}} %space between endnotes
\Xendnumberonlyfirstinline
\Xendlemmaseparator{:}
%\Xendafternumber{\newline} %should output newline after the line number; Error message "Illegal unit of measure (pt inserted). Wort1}{Kommentar1}{A}{}"
%\Xendinplaceofnumber[A]{\vspace{5em}} %changes vertical space between endnotes in the same line, Error message: Illegal unit of measure (pt inserted). Wort2}{Kommentar2}{A}{}


\begin{document}
	
	\beginnumbering
	
	
	\pstart
	\edtext{Wort1}{\Aendnote{Kommentar1}} und noch ein \edtext{Wort2}{\Aendnote{Kommentar2}}
	\newline
	Noch ein \edtext{Wort3}{\Aendnote{Kommentar3}} 
	\pend
	\endnumbering
	\newpage
	\doendnotes{A}
	
\end{document}

Could you please help us with that?
Thank you so much for all the effort, you are putting into this great package!
Best, 
Ingo

**Comment by maieul** [comment]
please open a new issue for this problem. I would look on that later.

**Comment by floriandk** [comment]
I'm sorry that I didn't have time to test this when you worked on it and asked for testing! The commands work fine in my project.

There's a tiny problem with defining indents: When I say 

    \documentclass[a5paper]{article}
    
    \usepackage[series={A},noeledsec,nofamiliar,noledgroup]{reledmac}
    
    \Xendhangindent{4cm}
    \Xendinplaceofnumber[A]{4cm}
    \Xendnumberonlyfirstinline[A]
    
    \begin{document}
    
    \beginnumbering
    \pstart
    \edtext{Lorem}{
      \Aendnote{A critical note}}
    \edtext{ipsum}{
      \Aendnote{An other critical note}}
     dolor sit amet, consectetur adipiscing elit. 
     \edtext{Fusce sed dolor libero. Aenean rutrum vestibulum lacus ut pretium. Fusce et auctor lectus. Ut et commodo quam, quis gravida orci. Nullam at risus elementum, suscipit enim a, pellentesque mi}
     {\lemma{Fusce\ldots mi}
     \Aendnote{Suspendisse vestibulum dignissim quam. Integer vel augue. Phasellus nulla purus, interdum ac, venenatis non, varius rutrum, leo. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.}}
    Morbi commodo, ligula vel consectetur accumsan, massa metus egestas velit, eu %
    \edtext{fringilla}{%
    	\Aendnote{test}}
     leo ante in turpis. Vivamus ut tellus sollicitudin, facilisis ipsum sit amet, tincidunt odio. Maecenas tincidunt dolor sed ante blandit tincidunt. Etiam vulputate ultricies facilisis.
    \pend
    \endnumbering
    
    \bigskip
    
    \setlength\parindent{0em}
    \doendnotes{A}
    
    \end{document}


the notes for "ipsum" and the 2nd to 4th line of "Fusce…" align, as I think they should. If I use 

    \Xendhangindent{4em}
    \Xendinplaceofnumber[A]{4em}

they don't. Is the size of the em being measured in relation to different font-sizes?
(It is not important -- I can work with cm; I just thought I would tell you)

**Comment by maieul** [comment]
plese open a new issue
